# Generated by Django 5.0.6 on 2024-07-04 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('simple_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(max_length=20)),
                ('hide', models.BooleanField(default=False)),
                ('delivery_message', models.TextField(blank=True)),
                ('has_stock', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('place', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_buyer', models.CharField(max_length=100)),
                ('social_user', models.CharField(max_length=50)),
                ('email_buyer', models.EmailField(max_length=120)),
                ('crypto', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('code_url', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('review_stars', models.IntegerField(default=0)),
                ('review_message', models.CharField(blank=True, max_length=150)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=30)),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('avatar', models.URLField(blank=True)),
                ('sold', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('tele_id', models.CharField(blank=True, max_length=20)),
                ('tele_token', models.CharField(blank=True, max_length=100)),
                ('discord_webhook', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('email_contact', models.CharField(blank=True, max_length=120)),
                ('telegram', models.CharField(blank=True, max_length=70)),
                ('discord', models.CharField(blank=True, max_length=70)),
                ('snapchat', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('other_payment', models.TextField(blank=True)),
                ('lock', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
