# Generated by Django 5.0.6 on 2024-07-04 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiers',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 4, 20, 53, 34, 49981, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='code_url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email_buyer',
            field=models.EmailField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='social_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='username_buyer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
