# Generated by Django 5.0.6 on 2024-07-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_expiers_alter_order_code_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiers',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
