# Generated by Django 5.0.7 on 2024-07-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_product_has_stock_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
