# Generated by Django 5.0.7 on 2024-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actually_paid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
